### ISSUE TITLE
Add control to field

### ISSUE THREAD

**Issue by luigiiorio30** [SchifName/MyGarage#1]
in "Add Cars Fragment", you must add character limit to input field, and remove the possibility to paste in production year, power, price, mileage field and fuel type.

![photo_2022-12-22_14-11-51 (1)](https://user-images.githubusercontent.com/39243394/209141972-36576a66-305f-461a-89ae-af3165964b85.jpg)

**Comment by luigiiorio30** [comment]
Remember to remove multi-line text in the field.

**Comment by SchifName** [comment]
Problem fixed with commit = " Issue #1 Add control to field (DONE) "
