### ISSUE TITLE
Add fuel type list

### ISSUE THREAD

**Issue by luigiiorio30** [SchifName/MyGarage#2]
You must add fuel type list to give to the final user a better user experience, and remember to remove the possibility to the user to paste in fuel field

![photo_2022-12-22_14-11-46](https://user-images.githubusercontent.com/39243394/209143044-cb89bd67-5593-4bb6-afd0-582ad37aaf39.jpg)

**Comment by SchifName** [comment]
Problem fixed with commit = " #2 Add fuel type list"
